# Generated by Django 4.0.4 on 2022-05-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='img',
            field=models.ImageField(blank=True, default='media/webtoon_img/default_image.jpeg', null=True, upload_to='webtoon_img/'),
        ),
    ]
