# Generated by Django 4.0.4 on 2022-05-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_alter_alldata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='webtoon_img/'),
        ),
    ]
