# Generated by Django 4.0.4 on 2022-06-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0004_alter_alldata_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='desc_noun',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
