# Generated by Django 4.0.4 on 2022-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0006_alter_alldata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='img',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
